a-getting_started.Rmd:
  path: dev/a-getting_started.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/a-getting-started.Rmd
  inflate:
    flat_file: dev/a-getting_started.Rmd
    vignette_name: a - Getting started
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
b1-linux_win.Rmd:
  path: dev/b1-linux_win.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/b1-setting-up-and-using-rix-on-linux-and-windows.Rmd
  inflate:
    flat_file: dev/b1-linux_win.Rmd
    vignette_name: b1 - Setting up and using rix on Linux and Windows
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
b2-macos.Rmd:
  path: dev/b2-macos.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/b2-setting-up-and-using-rix-on-macos.Rmd
  inflate:
    flat_file: dev/b2-macos.Rmd
    vignette_name: b2 - Setting up and using rix on macOS
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
c-building_envs_with_rix.Rmd:
  path: dev/c-building_envs_with_rix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/c-using-rix-to-build-project-specific-environments.Rmd
  inflate:
    flat_file: dev/c-building_envs_with_rix.Rmd
    vignette_name: c - Using rix to build project specific environments
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
d1-install_r_pkgs.Rmd:
  path: dev/d1-install_r_pkgs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/d1-installing-r-packages-in-a-nix-environment.Rmd
  inflate:
    flat_file: dev/d1-install_r_pkgs.Rmd
    vignette_name: d1 - Installing R packages in a Nix environment
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
d2-install_sys_pkgs.Rmd:
  path: dev/d2-install_sys_pkgs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/d2-installing-system-tools-and-texlive-packages-in-a-nix-environment.Rmd
  inflate:
    flat_file: dev/d2-install_sys_pkgs.Rmd
    vignette_name: d2 - Installing system tools and TexLive packages in a Nix environment
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
e-interactive_use.Rmd:
  path: dev/e-interactive_use.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/e-interactive-use.Rmd
  inflate:
    flat_file: dev/e-interactive_use.Rmd
    vignette_name: e - Interactive use
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_available_R.Rmd:
  path: dev/flat_available_R.Rmd
  state: active
  R: R/available_r.R
  tests: tests/testthat/test-available_r.R
  vignettes: []
  inflate:
    flat_file: dev/flat_available_R.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_cicd.Rmd:
  path: dev/flat_cicd.Rmd
  state: active
  R: R/tar_nix_ga.R
  tests: tests/testthat/test-tar_nix_ga.R
  vignettes: []
  inflate:
    flat_file: dev/flat_cicd.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_cran_archive.Rmd:
  path: dev/flat_cran_archive.Rmd
  state: active
  R: R/detect_versions.R
  tests: tests/testthat/test-detect_versions.R
  vignettes: []
  inflate:
    flat_file: dev/flat_cran_archive.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_data_doc.Rmd:
  path: dev/flat_data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_fetchers.Rmd:
  path: dev/flat_fetchers.Rmd
  state: active
  R: R/fetchgit.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_fetchers.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_find_rev.Rmd:
  path: dev/flat_find_rev.Rmd
  state: active
  R: R/find_rev.R
  tests: tests/testthat/test-find_rev.R
  vignettes: []
  inflate:
    flat_file: dev/flat_find_rev.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_get_latest.Rmd:
  path: dev/flat_get_latest.Rmd
  state: active
  R: R/get_latest.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_get_latest.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_get_os.Rmd:
  path: dev/flat_get_os.Rmd
  state: active
  R: R/detect_os.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_get_os.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_get_sri_hash_deps.Rmd:
  path: dev/flat_get_sri_hash_deps.Rmd
  state: active
  R: R/get_sri_hash_deps.R
  tests: tests/testthat/test-get_sri_hash_deps.R
  vignettes: []
  inflate:
    flat_file: dev/flat_get_sri_hash_deps.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_nix_build.Rmd:
  path: dev/flat_nix_build.Rmd
  state: active
  R: R/nix_build.R
  tests: tests/testthat/test-nix_build.R
  vignettes: []
  inflate:
    flat_file: dev/flat_nix_build.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_rix.Rmd:
  path: dev/flat_rix.Rmd
  state: active
  R: R/rix.R
  tests: tests/testthat/test-rix.R
  vignettes: []
  inflate:
    flat_file: dev/flat_rix.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_rix_init.Rmd:
  path: dev/flat_rix_init.Rmd
  state: active
  R: R/rix_init.R
  tests: tests/testthat/test-rix_init.R
  vignettes: []
  inflate:
    flat_file: dev/flat_rix_init.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_save_r_nix_revs.Rmd:
  path: dev/flat_save_r_nix_revs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-developers-vignette-save-the-nix-package-versions-data.Rmd
  inflate:
    flat_file: dev/flat_save_r_nix_revs.Rmd
    vignette_name: 'z - Developers Vignette: Save the Nix Package Versions data'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_with_nix.Rmd:
  path: dev/flat_with_nix.Rmd
  state: active
  R: R/with_nix.R
  tests: tests/testthat/test-with_nix.R
  vignettes: []
  inflate:
    flat_file: dev/flat_with_nix.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
flat_zzz.Rmd:
  path: dev/flat_zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/flat_zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
z-literate_programming.Rmd:
  path: dev/z-literate_programming.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-building-an-environment-for-literate-programming.Rmd
  inflate:
    flat_file: dev/z-literate_programming.Rmd
    vignette_name: 'z - Advanced topic: Building an environment for literate programming'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
z-pkgs_with_remotes.Rmd:
  path: dev/z-pkgs_with_remotes.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-handling-packages-with-remote-dependencies.Rmd
  inflate:
    flat_file: dev/z-pkgs_with_remotes.Rmd
    vignette_name: 'z - Advanced topic: Handling packages with remote dependencies'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
z-raps_with_nix.Rmd:
  path: dev/z-raps_with_nix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-reproducible-analytical-pipelines-with-nix.Rmd
  inflate:
    flat_file: dev/z-raps_with_nix.Rmd
    vignette_name: 'z - Advanced topic: Reproducible Analytical Pipelines with Nix'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
z-subshells.Rmd:
  path: dev/z-subshells.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/z-advanced-topic-running-r-or-shell-code-in-nix-from-r.Rmd
  inflate:
    flat_file: dev/z-subshells.Rmd
    vignette_name: 'z - Advanced topic: Running R or Shell Code in Nix from R'
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
