build_envs.Rmd:
  path: dev/build_envs.Rmd
  state: active
  R: R/find_rev.R
  tests: tests/testthat/test-find_rev.R
  vignettes: []
  inflate:
    flat_file: dev/build_envs.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
building_envs_with_rix.Rmd:
  path: dev/building_envs_with_rix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/building-reproducible-development-environments-with-rix.Rmd
  inflate:
    flat_file: dev/building_envs_with_rix.Rmd
    vignette_name: Building reproducible development environments with rix
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
cicd.Rmd:
  path: dev/cicd.Rmd
  state: active
  R: R/tar_nix_ga.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/cicd.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
cran_archive.Rmd:
  path: dev/cran_archive.Rmd
  state: active
  R: R/detect_versions.R
  tests: tests/testthat/test-detect_versions.R
  vignettes: []
  inflate:
    flat_file: dev/cran_archive.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
data_doc.Rmd:
  path: dev/data_doc.Rmd
  state: active
  R: R/included-datasets.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/data_doc.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
get_os.Rmd:
  path: dev/get_os.Rmd
  state: active
  R: R/detect_os.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/get_os.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
interactive_use.Rmd:
  path: dev/interactive_use.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/interactive-use.Rmd
  inflate:
    flat_file: dev/interactive_use.Rmd
    vignette_name: Interactive use
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
literate_programming.Rmd:
  path: dev/literate_programming.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/building-an-environment-for-literate-programming.Rmd
  inflate:
    flat_file: dev/literate_programming.Rmd
    vignette_name: Building an environment for literate programming
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
pkgs_with_remotes.Rmd:
  path: dev/pkgs_with_remotes.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/handling-packages-with-remote-dependencies.Rmd
  inflate:
    flat_file: dev/pkgs_with_remotes.Rmd
    vignette_name: Handling packages with remote dependencies
    open_vignette: true
    check: true
    document: true
    overwrite: ask
raps_with_nix.Rmd:
  path: dev/raps_with_nix.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/reproducible-analytical-pipelines-with-nix.Rmd
  inflate:
    flat_file: dev/raps_with_nix.Rmd
    vignette_name: Reproducible Analytical Pipelines with Nix
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
save_r_nix_revs.Rmd:
  path: dev/save_r_nix_revs.Rmd
  state: active
  R: []
  tests: []
  vignettes: vignettes/save-the-nix-package-versions-data.Rmd
  inflate:
    flat_file: dev/save_r_nix_revs.Rmd
    vignette_name: Save the Nix Package Versions data
    open_vignette: true
    check: true
    document: true
    overwrite: 'yes'
zzz.Rmd:
  path: dev/zzz.Rmd
  state: active
  R: R/zzz.R
  tests: []
  vignettes: []
  inflate:
    flat_file: dev/zzz.Rmd
    vignette_name: .na
    open_vignette: true
    check: true
    document: false
    overwrite: 'yes'
